# HE Tunnel Broker Manager configuration
# Configuration path after installation:
# /etc/he-tunnel/config.conf

SERVER_IPV4=
CLIENT_IPV4=
SERVER_IPV6=
CLIENT_IPV6=
ROUTED64=
ROUTED48=
DNS=Cloudflare
MTU=1280
AUTOSTART=0
FIREWALL=0
EXIT_MODE=48
